services:

  proxy:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: envoy-go
      args:
        ENVOY_VARIANT: contrib-dev
    depends_on:
      helloworld_service:
        condition: service_healthy
    ports:
    - "${PORT_PROXY:-10000}:10000"

  helloworld_service:
    build:
      context: ./helloworld_service
      target: aiohttp-hello-service
