services:

  proxy:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: envoy-go
      args:
        ENVOY_VARIANT: contrib-dev
    depends_on:
      helloworld_service:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
    ports:
    - "${PORT_PROXY:-10000}:10000"
    environment:
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_REGION=us-east-1
      - AWS_DISABLE_SSL=true
      - AWS_S3_FORCE_PATH_STYLE=true
      - AWS_S3_DISABLE_SSL=true

  helloworld_service:
    build:
      context: ./helloworld_service
      target: hello-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    ports:
    - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
    - "9000:9000"
    - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
    - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  minio_data:
